env:
  REPOSITORY_ROOT: "us-docker.pkg.dev/tc-platform-artifacts/theconversation"
  REPOSITORY_LIBRARY: "${REPOSITORY_ROOT}/library"
  IMAGE_VERSION: "1.5.2-r10"

agents:
  queue: small_amd64

steps:
  - label: ":docker: Build"
    plugins:
      conversation/hosted-agent-setup:
      docker-compose#v5.2.0:
        build: library
        push:
          - "library:$REPOSITORY_LIBRARY:build-$BUILDKITE_BUILD_NUMBER"

  - wait

  - label: ":eslint: Lint"
    command: npm run lint
    plugins:
      conversation/hosted-agent-setup:
      docker-compose#v5.2.0:
        run: library

  - label: ":npm: Test"
    command: npm run test
    plugins:
      conversation/hosted-agent-setup:
      docker-compose#v5.2.0:
        run: library

  - block: "Tag"
    branches: main

  - label: ":docker: Tag"
    branches: main
    plugins:
      conversation/hosted-agent-setup:
      docker-compose#v5.2.0:
        push:
          - "library:${REPOSITORY_LIBRARY}:${IMAGE_VERSION}"
